### ISSUE TITLE
Take over 

### ISSUE THREAD

**Issue by bartekbrak** [henry0312/pytest-codestyle#15]
Hi Henry, 

I am the owner of the package [pypi/pytest-pycodestyle](https://pypi.python.org/pypi/pytest-pycodestyle) which was a quick dirty fork which I lost interest in maintaining, should you be interested in taking over the name, let me know. 

it seems you are maintaingin your plugin well. 

code at https://github.com/bartekbrak/pytest-pycodestyle, one commit

I will be using fork rather than my own, so it seems best to remove mine enitrely.

**Comment by henry0312** [comment]
Hello Bartek,

Thank you for your proposal, and I would like to take over [pypi/pytest-pycodestyle](https://pypi.python.org/pypi/pytest-pycodestyle).

Best regards,
Tsukasa Omoto

**Comment by bartekbrak** [comment]
Hi Tsukasa, 

Done just now, do remove me as the other owner, I can't remove myself. 

Thank you for your work on this package.

**Comment by henry0312** [comment]
I've taken over [pytest-pycodestyle](https://pypi.python.org/pypi/pytest-pycodestyle).
Thank you a lot.
