### ISSUE TITLE
Ignore all errors

### ISSUE THREAD

**Issue by Peque** [henry0312/pytest-codestyle#18]
With `pytest-pep8` you may use `ALL` to ignore all errors:

```
[tool_pytest]
pep8ignore =
    docs/source/conf.py ALL
```

Is that possible with `pytest-codestyle` too?

**Comment by henry0312** [comment]
I'll check if [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/index.html) supports ignoring all errors.

**Comment by henry0312** [comment]
I read [pytest-pep8](https://bitbucket.org/pytest-dev/pytest-pep8)'s documents.

    .. warning::
    
        Running pep8 tests on your project is likely to cause a lot of 
        issues.  This plugin allows to configure on a per-project and
        per-file basis which errors or warnings to care about, see
        pep8ignore_.  As a preliminary advise, if you have 
        projects where you don't want to care at all about pep8 checks, 
        you can put configure it like this::
    
            # content of setup.cfg (or pytest.ini)
            [pytest]
            pep8ignore = * ALL

By the way, I wonder if you want to ignore all erros, you don't have to run pytest-codestyle.
Why do yout want this support?

**Comment by Peque** [comment]
I wanted to use it with specific files. In example: `docs/source/conf.py ALL` rather than `* ALL`.

**Comment by henry0312** [comment]
I'm sorry to tell you that I cannot implement your request function because I have to change the current config style.
Currently, you can run `pytest ... src tests`, which means exludeing `./docs` directory.
And patches are welcomed :)

**Comment by Peque** [comment]
No problem, thanks for your reply! :blush:
