### ISSUE TITLE
mark tests with codestyle

### ISSUE THREAD

**Issue by jwkvam** [henry0312/pytest-codestyle#3]
Similar to how pytest-pylint does:
https://github.com/carsongee/pytest-pylint/blob/master/pytest_pylint.py#L169

Then we can do stuff like:
```
pytest --codestyle -m codestyle
```
To only run codestyle checks.

If you like this I don't mind implementing it.

**Comment by henry0312** [comment]
@jwkvam can you check https://github.com/henry0312/pytest-codestyle/pull/4?
