### ISSUE TITLE
Implement an exclusion path list

### ISSUE THREAD

**Issue by mattwwarren** [henry0312/pytest-codestyle#32]
I'm working on a project that has a series of autogenerated source files that, sadly, do not conform to our desired guidelines. In order to prevent excessive changes to these autogenerated files, I would like to exclude them from being subjected to the codestyle tests.

I have a working patch and can make a pull request if this seems like a desirable feature.

**Comment by jjardon** [comment]
@henry0312 Hey, any chance to get this merged soon? This is the only blocker for us to migrate from pytest-pep8 to pytest-pycodestyle

**Comment by henry0312** [comment]
I've waited a response from @mattwwarren (https://github.com/henry0312/pytest-codestyle/pull/33).

**Comment by mattwwarren** [comment]
Sorry, I guess I've missed some github notifications. I'll look at this today.
