### ISSUE TITLE
Read native pycodestyle config (e.g. from setup.cfg)

### ISSUE THREAD

**Issue by datarods-svc** [henry0312/pytest-codestyle#51]
With regard to pycodestyle==1.4.0, I have to customize it by adding keys to the pytest config. This shouldn't be necessary! pytest-codestyle should cause pycodestyle to natively read its config as it would normally, e.g. from setup.cfg.

Until this is fixed, my setup.cfg has redundant configs:

```
[pycodestyle]
ignore = E731
max-line-length = 120

[tool:pytest]
addopts = --codestyle
codestyle_max_line_length = 120
codestyle_ignore = E731
```

The codestyle keys in the pytest config are effectively duplicated, and they shouldn't be necessary. Note that I want to retain the ability to run pycodestyle independently of pytest-codestyle too.

**Comment by ab-w** [comment]
For the sake of argument, the pytest plugins for black, mypy and pylint do read the respective native config files, and don't require duplication of the config.
